export const usuariosMock = [
  {
    id: "1",
    usuario: "analop",
    contrasena: "trader123",
    nombre: "Ana López",
    correo: "ana@example.com",
    telefono: "8888-1234",
    pais: "Costa Rica",
    rol: "Trader",
    estado: "activo",
    wallet: "0xABC123",
  },
  {
    id: "2",
    usuario: "cmendez",
    contrasena: "admin123",
    nombre: "Carlos Méndez",
    correo: "carlos@example.com",
    telefono: "8888-5678",
    pais: "Costa Rica",
    rol: "Admin",
    estado: "activo",
    wallet: "0xDEF456",
  },
  {
    id: "3",
    usuario: "ljimenez",
    contrasena: "analista123",
    nombre: "Laura Jiménez",
    correo: "laura@example.com",
    telefono: "8888-9999",
    pais: "Costa Rica",
    rol: "Analista",
    estado: "activo",
    wallet: "0xGHI789",
  },
];
